//
//  UITestingDemoUITests.m
//  UITestingDemoUITests
//
//  Created by Pham Chi Cong on 9/23/15.
//  Copyright © 2015 Transcosmos Technologic Arts. All rights reserved.
//

#import <XCTest/XCTest.h>

@interface UITestingDemoUITests : XCTestCase

@end

@implementation UITestingDemoUITests

- (void)setUp {
    [super setUp];
    
    // Put setup code here. This method is called before the invocation of each test method in the class.
    
    // In UI tests it is usually best to stop immediately when a failure occurs.
    self.continueAfterFailure = YES;
    // UI tests must launch the application that they test.
    //Doing this in setup will make sure it happens for each test method.
    [[[XCUIApplication alloc] init] launch];
    
    // In UI tests it’s important to set the initial state -
    //such as interface orientation - required for your tests before they run.
    //The setUp method is a good place to do this.
}

- (void)tearDown {
    // Put teardown code here. This method is called after the invocation of each test method in the class.
    [super tearDown];
}

- (void)testUIDeleteAllCells {
    XCUIApplication* app = [[XCUIApplication alloc] init];

    XCUIElement* devicesNavigationBar = app.navigationBars[@"Devices"];
    [devicesNavigationBar.buttons[@"Edit"] tap];
    
    XCUIElementQuery* tablesQuery = app.tables;
    while (tablesQuery.cells.count > 0) {
        int count = (int)tablesQuery.cells.count;
        XCUIElement* cell = [tablesQuery.cells elementBoundByIndex:0];
        XCUIElement* deletedCell = [cell.buttons matchingPredicate:[NSPredicate predicateWithFormat:@"label BEGINSWITH 'Delete'"]].element;
        [deletedCell tap];
        XCUIElement* deleteButton = [[[cell childrenMatchingType:XCUIElementTypeButton] matchingIdentifier:@"Delete"] elementBoundByIndex:0];
        [deleteButton tap];
        XCTAssertEqual(tablesQuery.cells.count, (count - 1));
    }
    XCTAssertEqual(tablesQuery.cells.count, 0);//Empty
    [devicesNavigationBar.buttons[@"Done"] tap];
    
    //Code is generated by UI Recording
//    [tablesQuery.cells.buttons[@"Delete iPhone 5"] tap];
//    XCUIElement *deleteButton = tablesQuery.cells.buttons[@"Delete"];
//    [deleteButton tap];
//    [tablesQuery.cells.buttons[@"Delete iPhone 5s"] tap];
//    [deleteButton tap];
//    [tablesQuery.cells.buttons[@"Delete iPhone 6"] tap];
//    [deleteButton tap];
//    [tablesQuery.cells.buttons[@"Delete iPhone 6s"] tap];
//    [deleteButton tap];
    
}
@end
